root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  bin = "app" # output binary name
  cmd = "go build -o ./tmp/app" # build command
  full_bin = "./tmp/app" # full path to binary file
  include_ext = ["go", "graphql"] # watch these file extensions
  exclude_dir = ["tmp", "vendor"] # exclude these directories
  exclude_file = ["air.toml"] # exclude these files
  cmd_args = [] # pass arguments to binary
  log = "debug" # log level
  send_interrupt = true # send SIGINT before restart

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
